#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
# 
#    http://shiny.rstudio.com/
#



library(dplyr)
library(ggplot2)
library(ggvis)
library(here)
library(rlang)
library(shiny)
library(shinycssloaders)
library(shinydashboard)
library(shinythemes)

# -----------------------------
# UI
# -----------------------------
#setwd(here("Data" , "Current Data"))
ui = dashboardPage(

  dashboardHeader(title = "West Brook Growth Predictions"),
  dashboardSidebar(
     sidebarMenu(
       
       menuItem("Main Effects" , tabName = "mainEffects") ,
       menuItem("Interactions", tabName = "interactions") ,
       menuItem("About" , tabName = "about")
     )),
     
  dashboardBody(
    tabItems(
      
      
      tabItem(tabName =  "mainEffects" , 
                      fluidRow(
                       
                        column(3,
                               wellPanel(
                                 selectInput('dataType1' , 
                                             'Data Type' , 
                                             c( 'Mean Growth mm/d' , 
                                                'Standard Deviation' , 
                                                'CV') ,
                                             'predGr')),
                               wellPanel(
                                 radioButtons('variable' , 
                                              'Variable To Display' , 
                                              c('Stream Temperature' , 
                                                'Stream Flow' , 
                                                'Estimated Abundance'  , 
                                                'Fish Length') , 
                                              'Stream Temperature')),
                               wellPanel(
                                 splitLayout( 
                                   checkboxGroupInput('ageA' , 
                                                      "Age" ,
                                                      c("Young of the Year" , 
                                                        "Adult" ) ,
                                                      "Adult"),
                                   checkboxGroupInput('specieSA' , 
                                                      'Species' , 
                                                      c('Brook Trout' , 
                                                        'Brown Trout'  , 
                                                        'Atlantic Salmon' ), 
                                                      'Brook Trout')) ,
                                 splitLayout(
                                   checkboxGroupInput("riverA" ,
                                                      "Tributary" , 
                                                      c("West Brook"  , 
                                                        "Open Large" , 
                                                        "Isolated Small" , 
                                                        "Open Small") ,
                                                      "West Brook" ) ,
                                   checkboxGroupInput("seasoNA" ,
                                                      "Season" ,
                                                      c('Spring',
                                                        'Summer' ,
                                                        'Fall' ,
                                                        'Winter') ,
                                                      'Spring' )),
                                 sliderInput("slider2A", label = h4("Iterations"), min = 10, 
                                             max = 1500, value =  1000)
                               )),
                        
                        # Show a plot of the generated distribution
                        column(9,
                               
                               conditionalPanel(condition = "input.variable == 'Stream Temperature'" ,
                                                withSpinner(plotOutput("plot1A", height = "700px"))),
                               conditionalPanel(condition = "input.variable == 'Stream Flow'" ,                 
                                                withSpinner( plotOutput("plot2A", height = "700px"))),
                               conditionalPanel(condition = "input.variable == 'Estimated Abundance'" ,                 
                                                withSpinner( plotOutput("plot3A", height = "700px"))),
                               conditionalPanel(condition = "input.variable == 'Fish Length'" ,                 
                                                withSpinner( plotOutput("plot4A", height = "700px"))))
                      )
                      
             ), 
             
         
                tabItem(tabName = "interactions",
                      fluidRow(
                        column(3,
                               
                               
                               wellPanel(
                                 selectInput('dataType2' , 
                                             'Data Type' , 
                                             c( 'Mean Growth mm/d' , 
                                                'Standard Deviation' , 
                                                'CV') ,
                                             'predGr')
                               ),
                               fluidRow(
                                 column(3 , tags$h3("Data_Filter"))),
                               conditionalPanel(condition = "input.facet1 == 'Age'",
                                                conditionalPanel(condition = "input.facet2 == 'River'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageAgeRiver" , 
                                                                                        "Age" ,
                                                                                        c("Young of the Year", 
                                                                                          "Adult" ) ,
                                                                                        "Adult"),
                                                                     radioButtons('speciesAgeRiver' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout' , 
                                                                                    'Atlantic Salmon'),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverAgeRiver" ,
                                                                                        "River" , 
                                                                                        c("West Brook"  , 
                                                                                          "Open Large" , 
                                                                                          "Isolated Small" , 
                                                                                          "Open Small" ) ,
                                                                                        "West Brook" ) ,
                                                                     radioButtons("seasonAgeRiver" ,
                                                                                  "Season" ,
                                                                                  c('Spring'  ,
                                                                                    'Summer' ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               conditionalPanel(condition = "input.facet1 == 'Age'",
                                                conditionalPanel(condition = "input.facet2 == 'Season'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageAgeSeason" , 
                                                                                        "Age" ,
                                                                                        c("Young of the Year" , 
                                                                                          "Adult" ) ,
                                                                                        "Adult"),
                                                                     radioButtons('speciesAgeSeason' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout'  , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverAgeSeason" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large"  , 
                                                                                    "Isolated Small"  , 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     checkboxGroupInput("seasonAgeSeason" ,
                                                                                        "Season" ,
                                                                                        c('Spring' ,
                                                                                          'Summer' ,
                                                                                          'Fall'  ,
                                                                                          'Winter' ) ,
                                                                                        'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'Age'",
                                                conditionalPanel(condition = "input.facet2 == 'Species'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageAgeSpecies" , 
                                                                                        "Age" ,
                                                                                        c("Young of the Year", 
                                                                                          "Adult" ) ,
                                                                                        "Adult"),
                                                                     checkboxGroupInput('speciesAgeSpecies' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' , 
                                                                                          'Brown Trout'  , 
                                                                                          'Atlantic Salmon' ),
                                                                                        'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverAgeSpecies" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large"  , 
                                                                                    "Isolated Small", 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     radioButtons("seasonAgeSpecies" ,
                                                                                  "Season" ,
                                                                                  c('Spring' ,
                                                                                    'Summer'  ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'River'",
                                                conditionalPanel(condition = "input.facet2 == 'Age'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageRiverAge" , 
                                                                                        "Age" ,
                                                                                        c("Young of the Year" , 
                                                                                          "Adult" ) ,
                                                                                        "Adult"),
                                                                     radioButtons('speciesRiverAge' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout', 
                                                                                    'Brown Trout' , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverRiverAge" ,
                                                                                        "River" , 
                                                                                        c("West Brook"  , 
                                                                                          "Open Large"  , 
                                                                                          "Isolated Small"  , 
                                                                                          "Open Small" ) ,
                                                                                        "West Brook" ) ,
                                                                     radioButtons("seasonRiverAge" ,
                                                                                  "Season" ,
                                                                                  c('Spring' ,
                                                                                    'Summer'  ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               conditionalPanel(condition = "input.facet1 == 'River'",
                                                conditionalPanel(condition = "input.facet2 == 'Season'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageRiverSeason" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year" , 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     radioButtons('speciesRiverSeason' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout' , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverRiverSeason" ,
                                                                                        "River" , 
                                                                                        c("West Brook"  , 
                                                                                          "Open Large"  , 
                                                                                          "Isolated Small"  , 
                                                                                          "Open Small" ) ,
                                                                                        "West Brook" ) ,
                                                                     checkboxGroupInput("seasonRiverSeason" ,
                                                                                        "Season" ,
                                                                                        c('Spring' ,
                                                                                          'Summer' ,
                                                                                          'Fall' ,
                                                                                          'Winter' ) ,
                                                                                        'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'River'",
                                                conditionalPanel(condition = "input.facet2 == 'Species'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageRiverSpecies" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year", 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     checkboxGroupInput('speciesRiverSpecies' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout', 
                                                                                          'Brown Trout'  , 
                                                                                          'Atlantic Salmon' ),
                                                                                        'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverRiverSpecies" ,
                                                                                        "River" , 
                                                                                        c("West Brook" , 
                                                                                          "Open Large" , 
                                                                                          "Isolated Small" , 
                                                                                          "Open Small" ) ,
                                                                                        "West Brook" ) ,
                                                                     radioButtons("seasonRiverSpecies" ,
                                                                                  "Season" ,
                                                                                  c('Spring' ,
                                                                                    'Summer'  ,
                                                                                    'Fall' ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               
                               
                               ### Season
                               
                               conditionalPanel(condition = "input.facet1 == 'Season'",
                                                conditionalPanel(condition = "input.facet2 == 'Age'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageSeasonAge" , 
                                                                                        "Age" ,
                                                                                        c("Young of the Year", 
                                                                                          "Adult") ,
                                                                                        "Adult"),
                                                                     radioButtons('speciesSeasonAge' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout' , 
                                                                                    'Atlantic Salmon'),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSeasonAge" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large" , 
                                                                                    "Isolated Small"  , 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     checkboxGroupInput("seasonSeasonAge" ,
                                                                                        "Season" ,
                                                                                        c('Spring'  ,
                                                                                          'Summer' ,
                                                                                          'Fall'  ,
                                                                                          'Winter' ) ,
                                                                                        'Spring' ))))),
                               conditionalPanel(condition = "input.facet1 == 'Season'",
                                                conditionalPanel(condition = "input.facet2 == 'River'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSeasonRiver" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year", 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     radioButtons('speciesSeasonRiver' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout', 
                                                                                    'Brown Trout'  , 
                                                                                    'Atlantic Salmon'),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverSeasonRiver" ,
                                                                                        "River" , 
                                                                                        c("West Brook" , 
                                                                                          "Open Large", 
                                                                                          "Isolated Small" , 
                                                                                          "Open Small" ) ,
                                                                                        "West Brook" ) ,
                                                                     checkboxGroupInput("seasonSeasonRiver" ,
                                                                                        "Season" ,
                                                                                        c('Spring'  ,
                                                                                          'Summer' ,
                                                                                          'Fall' ,
                                                                                          'Winter') ,
                                                                                        'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'Season'",
                                                conditionalPanel(condition = "input.facet2 == 'Species'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSeasonSpecies" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year", 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     checkboxGroupInput('speciesSeasonSpecies' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' , 
                                                                                          'Brown Trout'  , 
                                                                                          'Atlantic Salmon' ),
                                                                                        'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSeasonSpecies" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large" , 
                                                                                    "Isolated Small", 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     checkboxGroupInput("seasonSeasonSpecies" ,
                                                                                        "Season" ,
                                                                                        c('Spring' ,
                                                                                          'Summer' ,
                                                                                          'Fall' ,
                                                                                          'Winter' ) ,
                                                                                        'Spring' ))))),
                               
                               
                               
                               
                               conditionalPanel(condition = "input.facet1 == 'Species'",
                                                conditionalPanel(condition = "input.facet2 == 'Age'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageSpeciesAge" , 
                                                                                        "Age" ,
                                                                                        c("Young of the Year" , 
                                                                                          "Adult") ,
                                                                                        "Adult"),
                                                                     checkboxGroupInput('speciesSpeciesAge' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout', 
                                                                                          'Brown Trout'  , 
                                                                                          'Atlantic Salmon' ),
                                                                                        'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSpeciesAge" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large" , 
                                                                                    "Isolated Small"  , 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     radioButtons("seasonSpeciesAge" ,
                                                                                  "Season" ,
                                                                                  c('Spring' ,
                                                                                    'Summer' ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               conditionalPanel(condition = "input.facet1 == 'Species'",
                                                conditionalPanel(condition = "input.facet2 == 'River'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSpeciesRiver" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year", 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     checkboxGroupInput('speciesSpeciesRiver' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' , 
                                                                                          'Brown Trout'  , 
                                                                                          'Atlantic Salmon'),
                                                                                        'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverSpeciesRiver" ,
                                                                                        "River" , 
                                                                                        c("West Brook"  , 
                                                                                          "Open Large" , 
                                                                                          "Isolated Small" , 
                                                                                          "Open Small") ,
                                                                                        "West Brook" ) ,
                                                                     radioButtons("seasonSpeciesRiver" ,
                                                                                  "Season" ,
                                                                                  c('Spring'  ,
                                                                                    'Summer'  ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'Species'",
                                                conditionalPanel(condition = "input.facet2 == 'Season'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSpeciesSeason" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year" , 
                                                                                    "Adult") ,
                                                                                  "Adult"),
                                                                     checkboxGroupInput('speciesSpeciesSeason' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout', 
                                                                                          'Brown Trout', 
                                                                                          'Atlantic Salmon'),
                                                                                        'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSpeciesSeason" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large" , 
                                                                                    "Isolated Small", 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     checkboxGroupInput("seasonSpeciesSeason" ,
                                                                                        "Season" ,
                                                                                        c('Spring'  ,
                                                                                          'Summer'  ,
                                                                                          'Fall'  ,
                                                                                          'Winter' ) ,
                                                                                        'Spring' ))))),
                               
                               
                               
                               
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'Age'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageNoneAge" , 
                                                                                        "Age" ,
                                                                                        c("Young of the Year", 
                                                                                          "Adult" ) ,
                                                                                        "Adult"),
                                                                     radioButtons('speciesNoneAge' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout'  , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverNoneAge" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large" , 
                                                                                    "Isolated Small"  , 
                                                                                    "Open Small") ,
                                                                                  "West Brook" ) ,
                                                                     radioButtons("seasonNoneAge" ,
                                                                                  "Season" ,
                                                                                  c('Spring' ,
                                                                                    'Summer'  ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'River'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageNoneRiver" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year", 
                                                                                    "Adult") ,
                                                                                  "Adult"),
                                                                     radioButtons('speciesNoneRiver' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout'  , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverNoneRiver" ,
                                                                                        "River" , 
                                                                                        c("West Brook"  , 
                                                                                          "Open Large"  , 
                                                                                          "Isolated Small" , 
                                                                                          "Open Small" ) ,
                                                                                        "West Brook" ) ,
                                                                     radioButtons("seasonNoneRiver" ,
                                                                                  "Season" ,
                                                                                  c('Spring'  ,
                                                                                    'Summer'  ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'Season'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageNoneSeason" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year" , 
                                                                                    "Adult") ,
                                                                                  "Adult"),
                                                                     radioButtons('speciesNoneSeason' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout', 
                                                                                    'Brown Trout' , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverNoneSeason" ,
                                                                                  "River" , 
                                                                                  c("West Brook" , 
                                                                                    "Open Large"  , 
                                                                                    "Isolated Small" , 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     checkboxGroupInput("seasonNoneSeason" ,
                                                                                        "Season" ,
                                                                                        c('Spring'  ,
                                                                                          'Summer'  ,
                                                                                          'Fall'  ,
                                                                                          'Winter' ) ,
                                                                                        'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'Species'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageNoneSpecies" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year", 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     checkboxGroupInput('speciesNoneSpecies' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout' , 
                                                                                          'Brown Trout'  , 
                                                                                          'Atlantic Salmon' ),
                                                                                        'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverNoneSpecies" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large", 
                                                                                    "Isolated Small"  , 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     radioButtons("seasonNoneSpecies" ,
                                                                                  "Season" ,
                                                                                  c('Spring' ,
                                                                                    'Summer'  ,
                                                                                    'Fall' ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               
                               
                               
                               
                               conditionalPanel(condition = "input.facet1 == 'Age'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     checkboxGroupInput("ageAgeNone" , 
                                                                                        "Age" ,
                                                                                        c("Young of the Year" , 
                                                                                          "Adult") ,
                                                                                        "Adult"),
                                                                     radioButtons('speciesAgeNone' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout', 
                                                                                    'Brown Trout'  , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverAgeNone" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large" , 
                                                                                    "Isolated Small"  , 
                                                                                    "Open Small") ,
                                                                                  "West Brook" ) ,
                                                                     radioButtons("seasonAgeNone" ,
                                                                                  "Season" ,
                                                                                  c('Spring' ,
                                                                                    'Summer'  ,
                                                                                    'Fall' ,
                                                                                    'Winter') ,
                                                                                  'Spring' ))))),
                               conditionalPanel(condition = "input.facet1 == 'River'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageRiverNone" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year", 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     radioButtons('speciesRiverNone' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout'  , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     checkboxGroupInput("riverRiverNone" ,
                                                                                        "River" , 
                                                                                        c("West Brook" , 
                                                                                          "Open Large"  , 
                                                                                          "Isolated Small"  , 
                                                                                          "Open Small" ) ,
                                                                                        "West Brook" ) ,
                                                                     radioButtons("seasonRiverNone" ,
                                                                                  "Season" ,
                                                                                  c('Spring'  ,
                                                                                    'Summer' ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'Season'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSeasonNone" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year" , 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     radioButtons('speciesSeasonNone' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout'  , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSeasonNone" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large" , 
                                                                                    "Isolated Small" , 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     checkboxGroupInput("seasonSeasonNone" ,
                                                                                        "Season" ,
                                                                                        c('Spring'  ,
                                                                                          'Summer'  ,
                                                                                          'Fall'  ,
                                                                                          'Winter' ) ,
                                                                                        'Spring' ))))),
                               conditionalPanel(condition = "input.facet1 == 'Species'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageSpeciesNone" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year", 
                                                                                    "Adult") ,
                                                                                  "Adult"),
                                                                     checkboxGroupInput('speciesSpeciesNone' , 
                                                                                        'Species' , 
                                                                                        c('Brook Trout', 
                                                                                          'Brown Trout' , 
                                                                                          'Atlantic Salmon'),
                                                                                        'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverSpeciesNone" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large", 
                                                                                    "Isolated Small"  , 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     radioButtons("seasonSpeciesNone" ,
                                                                                  "Season" ,
                                                                                  c('Spring'  ,
                                                                                    'Summer'  ,
                                                                                    'Fall'  ,
                                                                                    'Winter') ,
                                                                                  'Spring' ))))),
                               
                               conditionalPanel(condition = "input.facet1 == 'None'",
                                                conditionalPanel(condition = "input.facet2 == 'None'",
                                                                 wellPanel(
                                                                   splitLayout(
                                                                     radioButtons("ageNoneNone" , 
                                                                                  "Age" ,
                                                                                  c("Young of the Year" , 
                                                                                    "Adult" ) ,
                                                                                  "Adult"),
                                                                     radioButtons('speciesNoneNone' , 
                                                                                  'Species' , 
                                                                                  c('Brook Trout' , 
                                                                                    'Brown Trout' , 
                                                                                    'Atlantic Salmon' ),
                                                                                  'Brook Trout' )) ,
                                                                   splitLayout(
                                                                     radioButtons("riverNoneNone" ,
                                                                                  "River" , 
                                                                                  c("West Brook"  , 
                                                                                    "Open Large" , 
                                                                                    "Isolated Small", 
                                                                                    "Open Small" ) ,
                                                                                  "West Brook" ) ,
                                                                     radioButtons("seasonNoneNone" ,
                                                                                  "Season" ,
                                                                                  c('Spring'  ,
                                                                                    'Summer' ,
                                                                                    'Fall'  ,
                                                                                    'Winter' ) ,
                                                                                  'Spring' ))))),
                               
                               
                               wellPanel(
                                 
                                 splitLayout(
                                   radioButtons('facet1' , 
                                                'Facet One' , 
                                                c ('Age' , 'River' , 'Season' , 'Species' , 'None') , 'None'),
                                   radioButtons('facet2' , 
                                                'Facet Two' , 
                                                c ('Age' , 'River' , 'Season' , 'Species' , 'None') , 'None'))
                               ),
                               fluidRow(
                                 column(3 , tags$h3("Graph_Controls"))),
                               wellPanel( 
                                 
                                 splitLayout(
                                   radioButtons("aXis" ,
                                                "X-Axis" , 
                                                c("Stream Temperature" = "temp"  , 
                                                  "Stream Flow" = "flow" , 
                                                  "Estimated Abundance" = "count" , 
                                                  "Fish Length" = "len" ) ,
                                                "temp" ) ,
                                   radioButtons("color" ,
                                                "Color" , 
                                                c("Stream Temperature" = "temp" , 
                                                  "Stream Flow" = "flow" , 
                                                  "Estimated Abundance" =  "count" , 
                                                  "Fish Length" = "len" ) ,
                                                "flow" )) ,
                                 # checkboxGroupInput("riverB" ,
                                 #"Slider" , 
                                 #c("temp" , "flow" , "count") ,
                                 #"count" )) ,
                                 
                                 
                                 conditionalPanel(condition = "input.aXis == 'temp'",
                                                  conditionalPanel(condition = "input.color == 'flow'",
                                                                   sliderInput("changeInTempCountOne",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInTempLengthOne",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'temp'",
                                                  conditionalPanel(condition = "input.color == 'count'",
                                                                   sliderInput("changeInTempFlowOne",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInTempLengthTwo",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'temp'",
                                                  conditionalPanel(condition = "input.color == 'len'",
                                                                   sliderInput("changeInTempCountTwo",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),
                                                                   sliderInput("changeInTempFlowTwo",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 
                                 
                                 
                                 
                                 conditionalPanel(condition = "input.aXis == 'flow'",
                                                  conditionalPanel(condition = "input.color == 'count'",
                                                                   sliderInput("changeInFlowLengthOne",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInFlowTempOne",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'flow'",
                                                  conditionalPanel(condition = "input.color == 'temp'",
                                                                   sliderInput("changeInFlowLengthTwo",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInFlowCountOne",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'flow'",
                                                  conditionalPanel(condition = "input.color == 'len'",
                                                                   sliderInput("changeInFlowTempTwo",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),
                                                                   sliderInput("changeInFlowCountTwo",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 
                                 
                                 conditionalPanel(condition = "input.aXis == 'count'",
                                                  conditionalPanel(condition = "input.color == 'flow'",
                                                                   sliderInput("changeInCountLengthOne",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInCountTempOne",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 conditionalPanel(condition = "input.aXis == 'count'",
                                                  conditionalPanel(condition = "input.color == 'temp'",
                                                                   sliderInput("changeInCountLengthTwo",
                                                                               "Standardized Fish Length",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInCountFlowOne",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 conditionalPanel(condition = "input.aXis == 'count'",
                                                  conditionalPanel(condition = "input.color == 'len'",
                                                                   sliderInput("changeInCountTempTwo",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),
                                                                   sliderInput("changeInCountFlowTwo",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 
                                 
                                 conditionalPanel(condition = "input.aXis == 'len'",
                                                  conditionalPanel(condition = "input.color == 'flow'",
                                                                   sliderInput("changeInLengthCountOne",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInLengthTempOne",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 conditionalPanel(condition = "input.aXis == 'len'",
                                                  conditionalPanel(condition = "input.color == 'temp'",
                                                                   sliderInput("changeInLengthCountTwo",
                                                                               "Standardized Estimated Abundance",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),    
                                                                   sliderInput("changeInLengthFlowOne",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))),
                                 
                                 conditionalPanel(condition = "input.aXis == 'len'",
                                                  conditionalPanel(condition = "input.color == 'count'",
                                                                   sliderInput("changeInLengthTempTwo",
                                                                               "Standardized Stream Temperature",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75),
                                                                   sliderInput("changeInLengthFlowTwo",
                                                                               "Standardized Stream Flow",
                                                                               min = -1.5,
                                                                               max = 1.5,
                                                                               value = 0 ,
                                                                               step = 0.75))), 
                                 sliderInput("slider2B", label = h4("Iterations"), min = 0, 
                                             max = 1500, value =  1000)
                               )),
                        
                        column(9,
                               withSpinner( plotOutput("plot1B" , height = "700px"))
                        )
                      )
             ),
      tabItem(tabName = "about", 
             box(title = "About" , width = 6,
                  p("Put Description of how the app works."))))))

